### ISSUE TITLE
Error with the example

### ISSUE THREAD

**Issue by nakamasato** [suzuki-shunsuke/pinact-action#586]
I tested with the following file:

```yaml
name: pinact
on:
  pull_request: {}
jobs:
  pinact:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@56efd2c1e82a807c939fe31dfbeb12fb73258566 # v0.1.1
```

and got the following error: 

```
Run tempfile=$(mktemp)
  tempfile=$(mktemp)
  git ls-files | grep -E '\.github/workflows/[^/]+\.ya?ml$' > "$tempfile"
  git ls-files | grep -E '^(.*/)?action\.ya?ml?' >> "$tempfile"
  {
    echo 'value<<EOF'
    cat "$tempfile"
    echo EOF
  } >> "$GITHUB_OUTPUT"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Error: Process completed with exit code 1.
```

Do you know the cause?
